#!/bin/bash

# this provides the definition of do_one (run one part of test)
# do_one [inlist] [output model] [LOGS directory]
# MESA_DIR=../../..
source "${MESA_DIR}/star/test_suite/test_suite_helpers"

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

do_one inlist_start_header start.mod LOGS_start
do_one inlist_to_sun_header sun.mod LOGS_to_sun

date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"

echo 'finished'

